### ISSUE TITLE
styles are not part of the bundle any more

### ISSUE THREAD

**Issue by Neddz** [brainhubeu/react-carousel#213]
**Describe the bug**
As `node-sass` was removed in the PR https://github.com/brainhubeu/react-carousel/pull/202, styles are not bundled any more.
Last working version: `1.10.39`

**To Reproduce**
1. Install the package `yarn add` 
2. Try to use it
3. You can no longer use the styles because they are not included and the module bundle will fail as well.

**Expected behaviour**
The library should include the styles as they are necessary for the library as documented in the `README.md`

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.1
- yarn 1.19.1

**Comment by yasso1am** [comment]
I have found the same thing, which is breaking my build. I fixed the version to `1.10.39` and it built just fine, however would be nice to know what's going on. Thanks for a great package.

**Comment by piotr-s-brainhub** [comment]
Sorry @Neddz @yasso1am 

Could you review https://github.com/brainhubeu/react-carousel/pull/215 ?

It was neglected because docs/ demo was working with local carousel code though you're right it failed with the newest `@brainhubeu/react-carousel` installed in `node_modules`. We noticed a build failing on `master` but it was previously failing as well due to breaking major dependencies which https://github.com/brainhubeu/react-carousel/pull/202 aimed to fix.

Thanks for your contribution. You're also welcome to report any missing features/ options or open PRs.

**Comment by piotr-s-brainhub** [comment]
@Neddz @yasso1am 

Now it should be fixed.
Also this https://github.com/brainhubeu/react-carousel/pull/217 was needed.

**Comment by piotr-s-brainhub** [comment]
@Neddz @yasso1am 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
