### ISSUE TITLE
Add changelog and semantic release

### ISSUE THREAD

**Issue by jonyw4** [brainhubeu/react-carousel#511]
**Describe the bug**
Hey guys, amazing project! I am using this project but every time that releases a new version i don't know what updated. 

**Expected behavior**
To publish in github releases the changelog, or something like that. I use https://github.com/semantic-release/semantic-release to publish and mantain a concise release log, but any similar project should work

**Screenshots**
Here its the screenshot what Renovate notify me. Notice that doesn't return any content
![Capturar](https://user-images.githubusercontent.com/14056669/83443670-84137d80-a420-11ea-99d8-70945419c3e6.PNG)

**Comment by piotr-s-brainhub** [comment]
@jonyw4 

Thanks for this suggestion. We've already had it in our plans (though not written as a GitHub issue). Your issue makes it more probable to be done in the nearest future. In order to yet increase this probability, you can invite your colleagues to like (👍) this issue.

We're also planning the CI build to fail for missing release notes in order to avoid forgetting about that.

**Comment by jonyw4** [comment]
Any update on this?

**Comment by piotr-s-brainhub** [comment]
@jonyw4 

It's in progress though we're planning to do that only for future versions.

**Comment by RobertHebel** [comment]
@jonyw4 from version 2.0 each release will contain release notes. Semantic-release is already on `rc` branch
