### ISSUE TITLE
minDraggableOffset not working

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#540]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/540)

It is: `minDraggableOffset` even if set to 0 or 1, still requires a large offset to change the slide.

It should be: it should require a move with at least the value of the `minDraggableOffset`

Code applicable in the clickable demo/ docs:
```
<Carousel
  slidesPerPage={2}
  infinite
  minDraggableOffset={0}
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```

Desktop:
- OS: Mac OS X 10.14.6
- Browser: Chrome 83.0.4103.97

Mobile
- OS: iOS 12.4.5
- Browser: Safari

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by RobertHebel** [comment]
@piotr-s-brainhub distance to change slide equals 50% of slide width. To change that behavior you can use `keepDirectionWhenDragging` prop. 

minDraggableOffset allows users to click on a slide that contains a link and its default value is sufficient for all cases. That's why it will be removed in the carousel v2
