### ISSUE TITLE
Could not find a declaration file for module '@brainhubeu/react-carousel'

### ISSUE THREAD

**Issue by tommwenda** [brainhubeu/react-carousel#60]
When using on react 16.2.0 the error below is thrown:
`ERROR in ./node_modules/@brainhubeu/react-carousel/lib/style.css
[0] Module parse failed: Unexpected token (1:0)
[0] You may need an appropriate loader to handle this file type.`

The IDE shows the following warning:

`[ts]
Could not find a declaration file for module '@brainhubeu/react-carousel'. '/path_to_project/node_modules/@brainhubeu/react-carousel/lib/react-carousel.js' implicitly has an 'any' type.`

This is simple usage by following the instructions on https://brainhubeu.github.io/react-carousel/docs/gettingStarted

**Comment by szulcd2** [comment]
hi,
regarding the error that is thrown, seems like your project configuration does not allow importing `.css` files. Are you using [webpack](https://webpack.js.org/) to build a project? If so, you can use [style-loader](https://github.com/webpack-contrib/style-loader) to solve the issue. If not, let us know what are you using and we will help you up.

Regarding typescript warning, that's because we still haven't delivered types for Typescript (although it is in our plans). We will try to fix it as soon as possible.

Let us know if it helps. Good luck!

**Comment by damian-brainhub** [comment]
hi,
regarding the error that is thrown, seems like your project configuration does not allow importing .css files. Are you using webpack to build a project? If so, you can use style-loader to solve the issue. If not, let us know what are you using and we will help you up.

Regarding typescript warning, that's because we still haven't delivered types for Typescript (although it is in our plans). We will try to fix it as soon as possible.

Let us know if it helps. Good luck!

**Comment by SoaresMG** [comment]
Is there news about TypeScript definitions?

**Comment by jackall3n** [comment]
I've created the types here (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37617).

Just install `@types/brainhubeu__react-carousel`

**Comment by pierzchalatomasz** [comment]
Types are ok except of the `slides` prop. It should be array of `any` elements instead of `img`.

**Comment by piotr-s-brainhub** [comment]
That PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41770 should have fixed this issue.

@pierzchalatomasz can we close this issue?

**Comment by pierzchalatomasz** [comment]
@piotr-s-brainhub Sure, we can :)

**Comment by piotr-s-brainhub** [comment]
@tommwenda @SoaresMG 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by SoaresMG** [comment]
@piotr-s-brainhub didn't see that message, answered it just now

**Comment by piotr-s-brainhub** [comment]
much thanks @SoaresMG
